# Generated by Django 3.1.4 on 2021-02-08 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='duree',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='idenseignant',
            field=models.ForeignKey(blank=True, db_column='IDEnseignant', null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom_reservation_app.enseignants'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='idetudiant',
            field=models.ForeignKey(blank=True, db_column='IDEtudiant', null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom_reservation_app.etudiants'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='idsalle',
            field=models.ForeignKey(db_column='IDSalle', on_delete=django.db.models.deletion.CASCADE, to='classroom_reservation_app.salle'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='type',
            field=models.CharField(db_column='Type', max_length=30),
        ),
    ]
