# Generated by Django 3.1.4 on 2021-02-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_reservation_app', '0002_auto_20210208_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='heure_debut',
            field=models.IntegerField(db_column='Heure_debut'),
        ),
    ]
