# Generated by Django 3.1.4 on 2021-02-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_reservation_app', '0003_auto_20210209_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batiment',
            name='heure_fermeture',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='heure_ouverture',
            field=models.IntegerField(),
        ),
    ]
